/* eslint-disable no-dupe-keys */
// Estrutura base dos 16 confrontos — slots "bestThird" são resolvidos dinamicamente
export const R32_FIXTURE_BASES = [
  { id:"r32-0",  label:"M73", home:{type:"winner",  g:"E"}, away:{type:"bestThird", eligible:["A","B","C","D","F"]} },
  { id:"r32-1",  label:"M74", home:{type:"winner",  g:"I"}, away:{type:"bestThird", eligible:["C","D","F","G","H"]} },
  { id:"r32-2",  label:"M75", home:{type:"runnerUp",g:"A"}, away:{type:"runnerUp",  g:"B"} },
  { id:"r32-3",  label:"M76", home:{type:"winner",  g:"F"}, away:{type:"runnerUp",  g:"C"} },
  { id:"r32-4",  label:"M77", home:{type:"runnerUp",g:"K"}, away:{type:"runnerUp",  g:"L"} },
  { id:"r32-5",  label:"M78", home:{type:"winner",  g:"H"}, away:{type:"runnerUp",  g:"J"} },
  { id:"r32-6",  label:"M79", home:{type:"winner",  g:"D"}, away:{type:"bestThird", eligible:["B","E","F","I","J"]} },
  { id:"r32-7",  label:"M80", home:{type:"winner",  g:"G"}, away:{type:"bestThird", eligible:["A","E","H","I","J"]} },
  { id:"r32-8",  label:"M81", home:{type:"winner",  g:"C"}, away:{type:"runnerUp",  g:"F"} },
  { id:"r32-9",  label:"M82", home:{type:"runnerUp",g:"E"}, away:{type:"runnerUp",  g:"I"} },
  { id:"r32-10", label:"M83", home:{type:"winner",  g:"A"}, away:{type:"bestThird", eligible:["C","E","F","H","I"]} },
  { id:"r32-11", label:"M84", home:{type:"winner",  g:"L"}, away:{type:"bestThird", eligible:["E","H","I","J","K"]} },
  { id:"r32-12", label:"M85", home:{type:"winner",  g:"J"}, away:{type:"runnerUp",  g:"H"} },
  { id:"r32-13", label:"M86", home:{type:"runnerUp",g:"D"}, away:{type:"runnerUp",  g:"G"} },
  { id:"r32-14", label:"M87", home:{type:"winner",  g:"B"}, away:{type:"bestThird", eligible:["E","F","G","I","J"]} },
  { id:"r32-15", label:"M88", home:{type:"winner",  g:"K"}, away:{type:"bestThird", eligible:["D","E","I","J","L"]} },
];

 
export const _c = (a,b,d,e,g,i,k,l) => ({A:a,B:b,D:d,E:e,G:g,I:i,K:k,L:l});
export const ANNEX_C = {
  // ── 1-9: sem A,B,C ──
  "EFGHIJKL":_c("E","J","I","F","H","G","L","K"),
  "DFGHIJKL":_c("H","G","I","D","J","F","L","K"),
  "DEGHIJKL":_c("E","J","I","D","H","G","L","K"),
  "DEFHIJKL":_c("E","J","I","D","H","F","L","K"),
  "DEFGIJKL":_c("E","G","I","D","J","F","L","K"),
  "DEFGHJKL":_c("E","G","J","D","H","F","L","K"),
  "DEFGHIKL":_c("E","G","I","D","H","F","L","K"),
  "DEFGHIJL":_c("E","G","J","D","H","F","L","I"),
  "DEFGHIJK":_c("E","G","J","D","H","F","I","K"),
  // ── 10-45: com C ──
  "CFGHIJKL":_c("H","G","I","C","J","F","L","K"),
  "CEGHIJKL":_c("E","J","I","C","H","G","L","K"),
  "CEFHIJKL":_c("E","J","I","C","H","F","L","K"),
  "CEFGIJKL":_c("E","G","I","C","J","F","L","K"),
  "CEFGHJKL":_c("E","G","J","C","H","F","L","K"),
  "CEFGHIKL":_c("E","G","I","C","H","F","L","K"),
  "CEFGHIJL":_c("E","G","J","C","H","F","L","I"),
  "CEFGHIJK":_c("E","G","J","C","H","F","I","K"),
  "CDGHIJKL":_c("H","G","I","C","J","D","L","K"),
  "CDFHIJKL":_c("C","J","I","D","H","F","L","K"),
  "CDFGIJKL":_c("C","G","I","D","J","F","L","K"),
  "CDFGHJKL":_c("C","G","J","D","H","F","L","K"),
  "CDFGHIKL":_c("C","G","I","D","H","F","L","K"),
  "CDFGHIJL":_c("C","G","J","D","H","F","L","I"),
  "CDFGHIJK":_c("C","G","J","D","H","F","I","K"),
  "CDEHIJKL":_c("E","J","I","C","H","D","L","K"),
  "CDEGHIJKL":_c("E","G","J","C","H","D","L","K"),
  "CDEGIJKL":_c("E","G","I","C","J","D","L","K"),
  "CDEGHJKL":_c("E","G","J","C","H","D","L","K"),
  "CDEGHIKL":_c("E","G","I","C","H","D","L","K"),
  "CDEGHIJL":_c("E","G","J","C","H","D","L","I"),
  "CDEGHIJK":_c("E","G","J","C","H","D","I","K"),
  "CDEFIJKL":_c("C","J","E","D","I","F","L","K"),
  "CDEFHJKL":_c("C","J","E","D","H","F","L","K"),
  "CDEFHIKL":_c("C","E","I","D","H","F","L","K"),
  "CDEFHIJL":_c("C","J","E","D","H","F","L","I"),
  "CDEFHIJK":_c("C","J","E","D","H","F","I","K"),
  "CDEFGJKL":_c("C","G","E","D","J","F","L","K"),
  "CDEFGIKL":_c("C","G","E","D","I","F","L","K"),
  "CDEFGIJL":_c("C","G","E","D","J","F","L","I"),
  "CDEFGIJK":_c("C","G","E","D","J","F","I","K"),
  "CDEFGHKL":_c("C","G","E","D","H","F","L","K"),
  "CDEFGHJL":_c("C","G","J","D","H","F","L","E"),
  "CDEFGHJK":_c("C","G","J","D","H","F","E","K"),
  "CDEFGHIL":_c("C","G","E","D","H","F","L","I"),
  "CDEFGHIK":_c("C","G","E","D","H","F","I","K"),
  "CDEFGHIJ":_c("C","G","J","D","H","F","E","I"),  // combo 45 ← mais provável
  // ── 46-81: com B ──
  "BFGHIJKL":_c("H","J","B","F","I","G","L","K"),
  "BEGHIJKL":_c("E","J","I","B","H","G","L","K"),
  "BEFHIJKL":_c("E","J","B","F","I","H","L","K"),
  "BEFGIJKL":_c("E","J","B","F","I","G","L","K"),
  "BEFGHJKL":_c("E","J","B","F","H","G","L","K"),
  "BEFGHIKL":_c("E","G","B","F","I","H","L","K"),
  "BEFGHIJL":_c("E","J","B","F","H","G","L","I"),
  "BEFGHIJK":_c("E","J","B","F","H","G","I","K"),
  "BDGHIJKL":_c("H","J","B","D","I","G","L","K"),
  "BDFHIJKL":_c("H","J","B","D","I","F","L","K"),
  "BDFGIJKL":_c("I","G","B","D","J","F","L","K"),
  "BDFGHJKL":_c("H","G","B","D","J","F","L","K"),
  "BDFGHIKL":_c("H","G","B","D","I","F","L","K"),
  "BDFGHIJL":_c("H","G","B","D","J","F","L","I"),
  "BDFGHIJK":_c("H","G","B","D","J","F","I","K"),
  "BDEHIJKL":_c("E","J","B","D","I","H","L","K"),
  "BDEGIJKL":_c("E","J","B","D","I","G","L","K"),
  "BDEGHJKL":_c("E","J","B","D","H","G","L","K"),
  "BDEGHIKL":_c("E","G","B","D","I","H","L","K"),
  "BDEGHIJL":_c("E","J","B","D","H","G","L","I"),
  "BDEGHIJK":_c("E","J","B","D","H","G","I","K"),
  "BDEFIJKL":_c("E","J","B","D","I","F","L","K"),
  "BDEFHJKL":_c("E","J","B","D","H","F","L","K"),
  "BDEFHIKL":_c("E","I","B","D","H","F","L","K"),
  "BDEFHIJL":_c("E","J","B","D","H","F","L","I"),
  "BDEFHIJK":_c("E","J","B","D","H","F","I","K"),
  "BDEFGJKL":_c("E","G","B","D","J","F","L","K"),
  "BDEFGIKL":_c("E","G","B","D","I","F","L","K"),
  "BDEFGIJL":_c("E","G","B","D","J","F","L","I"),
  "BDEFGIJK":_c("E","G","B","D","J","F","I","K"),
  "BDEFGHKL":_c("E","G","B","D","H","F","L","K"),
  "BDEFGHJL":_c("H","G","B","D","J","F","L","E"),
  "BDEFGHJK":_c("H","G","B","D","J","F","E","K"),
  "BDEFGHIL":_c("E","G","B","D","H","F","L","I"),
  "BDEFGHIK":_c("E","G","B","D","H","F","I","K"),
  "BDEFGHIJ":_c("H","G","B","D","J","F","E","I"),
  // ── 82-127: com B e C ──
  "BCGHIJKL":_c("H","J","B","C","I","G","L","K"),
  "BCFHIJKL":_c("H","J","B","C","I","F","L","K"),
  "BCFGIJKL":_c("I","G","B","C","J","F","L","K"),
  "BCFGHJKL":_c("H","G","B","C","J","F","L","K"),
  "BCFGHIKL":_c("H","G","B","C","I","F","L","K"),
  "BCFGHIJL":_c("H","G","B","C","J","F","L","I"),
  "BCFGHIJK":_c("H","G","B","C","J","F","I","K"),
  "BCEHIJKL":_c("E","J","B","C","I","H","L","K"),
  "BCEGIJKL":_c("E","J","B","C","I","G","L","K"),
  "BCEGHJKL":_c("E","J","B","C","H","G","L","K"),
  "BCEGHIKL":_c("E","G","B","C","I","H","L","K"),
  "BCEGHIJL":_c("E","J","B","C","H","G","L","I"),
  "BCEGHIJK":_c("E","J","B","C","H","G","I","K"),
  "BCEFIJKL":_c("E","J","B","C","I","F","L","K"),
  "BCEFHJKL":_c("E","J","B","C","H","F","L","K"),
  "BCEFHIKL":_c("E","I","B","C","H","F","L","K"),
  "BCEFHIJL":_c("E","J","B","C","H","F","L","I"),
  "BCEFHIJK":_c("E","J","B","C","H","F","I","K"),
  "BCEFGJKL":_c("E","G","B","C","J","F","L","K"),
  "BCEFGIKL":_c("E","G","B","C","I","F","L","K"),
  "BCEFGIJL":_c("E","G","B","C","J","F","L","I"),
  "BCEFGIJK":_c("E","G","B","C","J","F","I","K"),
  "BCEFGHKL":_c("E","G","B","C","H","F","L","K"),
  "BCEFGHJL":_c("H","G","B","C","J","F","L","E"),
  "BCEFGHJK":_c("H","G","B","C","J","F","E","K"),
  "BCEFGHIL":_c("E","G","B","C","H","F","L","I"),
  "BCEFGHIK":_c("E","G","B","C","H","F","I","K"),
  "BCEFGHIJ":_c("H","G","B","C","J","F","E","I"),
  "BCDHIJKL":_c("H","J","B","C","I","D","L","K"),
  "BCDGIJKL":_c("I","G","B","C","J","D","L","K"),
  "BCDGHJKL":_c("H","G","B","C","J","D","L","K"),
  "BCDGHIKL":_c("H","G","B","C","I","D","L","K"),
  "BCDGHIJL":_c("H","G","B","C","J","D","L","I"),
  "BCDGHIJK":_c("H","G","B","C","J","D","I","K"),
  "BCDFIJKL":_c("C","J","B","D","I","F","L","K"),
  "BCDFHJKL":_c("C","J","B","D","H","F","L","K"),
  "BCDFHIKL":_c("C","I","B","D","H","F","L","K"),
  "BCDFHIJL":_c("C","J","B","D","H","F","L","I"),
  "BCDFHIJK":_c("C","J","B","D","H","F","I","K"),
  "BCDFGJKL":_c("C","G","B","D","J","F","L","K"),
  "BCDFGIKL":_c("C","G","B","D","I","F","L","K"),
  "BCDFGIJL":_c("C","G","B","D","J","F","L","I"),
  "BCDFGIJK":_c("C","G","B","D","J","F","I","K"),
  "BCDFGHKL":_c("C","G","B","D","H","F","L","K"),
  "BCDFGHJL":_c("H","G","B","D","J","F","L","C"),
  "BCDFGHJK":_c("H","G","B","D","J","F","C","K"),
  "BCDFGHIL":_c("C","G","B","D","H","F","L","I"),
  "BCDFGHIK":_c("C","G","B","D","H","F","I","K"),
  "BCDFGHIJ":_c("H","G","B","D","J","F","C","I"),
  "BCDEHIJKL":_c("E","J","B","C","I","D","L","K"),
  "BCDEGHJKL":_c("E","J","B","C","H","D","L","K"),
  "BCDEGHIJK":_c("E","J","B","C","H","D","I","K"),
  "BCDEFIJKL":_c("C","J","B","D","I","F","L","K"),
  "BCDEFGIJK":_c("C","G","B","D","J","F","I","K"),
  "BCDEFGHIJ":_c("H","G","B","D","J","F","C","I"),
  // ── Com A — derivadas pelo padrão do Anexo C ──
  "AFGHIJKL":_c("F","A","I","G","H","J","L","K"),
  "AEFGHIJL":_c("E","A","J","F","H","G","L","I"),
  "AEFGHIJK":_c("E","A","J","F","H","G","I","K"),
  "ADGHIJKL":_c("H","A","I","D","J","G","L","K"),
  "ADEHIJKL":_c("E","A","I","D","H","G","L","K"),
  "ADEFGHIJK":_c("E","A","J","D","H","F","I","K"),
  "ACFGHIJKL":_c("H","A","I","C","J","F","L","K"),
  "ACDFGHIJK":_c("C","A","J","D","H","F","I","K"),
  "ABFGHIJKL":_c("F","A","B","G","H","J","L","K"),
  "ABCGHIJKL":_c("H","A","B","C","J","G","L","K"),
  "ABCDFGHIJK":_c("C","A","B","D","H","F","I","K"),
  "ABCDEFGIJK":_c("C","A","E","D","J","F","I","K"),
  "ABCDEFGHKL":_c("B","A","C","D","E","F","L","K"),
  "ABCDEFGHIJ":_c("B","A","C","D","E","F","G","H"),  // cenário do GE
  "ABCDEFGHIL":_c("B","A","C","D","E","F","L","I"),
  "ABCDEFGHIK":_c("B","A","C","D","E","F","I","K"),
  "ABCDEFGH":  _c("B","A","C","D","E","F","G","H"),  // 8 grupos A-H
  "ABCDEFGI":  _c("B","A","C","D","E","F","G","I"),
  "ABCDEFGJ":  _c("B","A","C","D","E","F","G","J"),
  "ABCDEFGK":  _c("B","A","C","D","E","F","K","G"),
  "ABCDEFGL":  _c("B","A","C","D","E","F","G","L"),
  "ABCDEFHI":  _c("B","A","C","D","H","F","I","E"),
  "ABCDEFHJ":  _c("B","A","C","D","H","F","J","E"),
  "ABCDEFHK":  _c("B","A","C","D","H","F","K","E"),
  "ABCDEFHL":  _c("B","A","C","D","H","F","E","L"),
  "ABCDEFIJ":  _c("B","A","C","D","I","F","J","E"),
  "ABCDEIJK":  _c("B","A","C","D","I","E","K","J"),
  "ABCDEIJL":  _c("B","A","C","D","I","E","J","L"),
  // Gerado pelos PRESET_SCORES atuais: 3ºs de A,B,D,E,F,I,J,L no top-8
  "ABDEFIJL":  _c("F","J","B","A","E","D","L","I"),
  "ABDEFGIL":  _c("E","G","B","D","A","F","L","I"),
};
 
export function resolveThirdSlots(qualifiedGroups) {
  const key = [...qualifiedGroups].sort().join("");
  if (ANNEX_C[key]) return ANNEX_C[key];
  const winnerSlots = ["A","B","D","E","G","I","K","L"];
  const thirds = [...qualifiedGroups].sort();
  function backtrack(slotIndex, used, assignment) {
    if (slotIndex === winnerSlots.length) return assignment;
    const ws = winnerSlots[slotIndex];
    for (const g of thirds) {
      if (!used.has(g) && g !== ws) {
        used.add(g);
        assignment[ws] = g;
        const result = backtrack(slotIndex + 1, used, assignment);
        if (result) return result;
        used.delete(g);
        delete assignment[ws];
      }
    }
    return null;
  }
  return backtrack(0, new Set(), {}) ?? {};
}
